version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/dbname
      JWT_SECRET: your_jwt_secret
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server